/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        canvas: '#FFFFFF',
        surface: '#FFFFFF',
        'surface-raised': '#FFFFFF',
        module: '#FFFFFF',
        'module-muted': '#ECECEA',
        ink: '#111111',
        muted: '#7C7C78',
        subtle: '#A6A6A1',
        border: '#DEDEDA',
        line: '#D4D4CF',
        primary: '#141414',
        'primary-dark': '#050505',
        'primary-soft': '#E7E7E3',
        'onboarding-canvas': '#F2F2F0',
        'onboarding-surface': '#FFFFFF',
        'onboarding-surface-muted': '#ECECEA',
        'onboarding-text': '#111111',
        'onboarding-muted': '#7C7C78',
        'onboarding-line': '#D4D4CF',
        'onboarding-accent': '#111111',
        'onboarding-accent-soft': '#ECECEA',
        sage: '#7A9B76',
        'sage-dark': '#506D4F',
        'sage-soft': '#DDE7D8',
        water: '#7895A6',
        'water-soft': '#DCE8ED',
        gold: '#B59A5B',
        'gold-soft': '#EFE4C8',
        clay: '#A87962',
        'clay-soft': '#E9D8CF',
        error: '#A45E54',
        'error-soft': '#F1DDD7',
        'dark-canvas': '#1B2028',
        'dark-surface': '#252B34',
        'dark-ink': '#F2EEE6',
        'dark-muted': '#AEB5BE',
      },
      borderRadius: {
        app: '30px',
        module: '32px',
        control: '18px',
      },
      fontFamily: {
        sans: ['System'],
        rounded: ['System'],
      },
    },
  },
  plugins: [],
};
